FROM eclipse-temurin:17-jdk-alpine
RUN apk add curl
VOLUME /tmp
EXPOSE 8080
ADD target/Springboot-aws-deploy-service.jar Springboot-aws-deploy-service.jar
ENTRYPOINT ["java","jar","/Springboot-aws-deploy-service.jar"] 